#! /bin/bash

app=adminer

domain=$1
path=$2
admin=$3

version=4.1.0

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
  echo "Wrong user"
  exit 1
fi

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app domain -v "$domain"
sudo yunohost app setting $app path -v "$path"

#create path for copying
final_path=/var/www/$app
sudo mkdir -p $final_path

#copy files to final folder and set permissions
sudo cp -R ../sources/adminer-$version.php $final_path/index.php

#setting permissions
sudo chmod 640 $final_path/index.php
sudo chown root:www-data $final_path/index.php

#getting mysql root pass
mysql_pass=$(sudo cat /etc/yunohost/mysql)
sudo sed -i "s@USERNAME_YNH@root@g" $final_path/index.php
sudo sed -i "s@PASSWORD_YNH@$mysql_pass@g" $final_path/index.php
sudo sed -i "s@DATABASE_YNH@mysql@g" $final_path/index.php


#configure nginx settings
sudo sed -i "s@YNH_EXAMPLE_PATH@$path@g" ../conf/nginx.conf
sudo sed -i "s@YNH_EXAMPLE_ALIAS@$final_path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

#adding admin to the allowed users
sudo yunohost app addaccess $app -u $admin

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf