#! /bin/bash

app=adminer

#retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app admin)

# Remove trailing "/" for next commands
path=${path%/}

#copy files to final folder and set permissions
sudo cp -R ../sources/adminer-$version.php $final_path/index.php

#setting permissions
sudo chmod 640 $final_path/index.php
sudo chown root:www-data $final_path/index.php

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf